# Generated by Django 4.2.27 on 2026-01-19 16:57

from django.db import migrations

def seed_products(apps, schema_editor):
    Product = apps.get_model("payments", "Product")

    Product.objects.get_or_create(
        product_type="subscription",
        defaults={
            "name": "Assinatura Mensal",
            "price": 29.90,
        }
    )

    Product.objects.get_or_create(
        product_type="content",
        defaults={
            "name": "Conteúdo Premium",
            "price": 0.90,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_products),
    ]
