# Generated by Django 4.2.27 on 2026-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_image_id_alter_payment_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
