# Generated by Django 4.2.27 on 2026-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
