# Generated by Django 4.2.27 on 2026-01-21 20:33

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/', validators=[payments.models.validate_media_file]),
        ),
    ]
